name: Kuiz
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.0
  firebase_auth: ^4.4.0
  flutter_spinkit: ^5.2.0
  connectivity_plus : ^4.0.1
  animated_text_kit: ^4.2.2
  google_maps_flutter: ^2.3.0
  url_launcher: ^6.1.11

  flutter:
    sdk: flutter
  http: ^0.13.5
  firebase_database: ^10.1.2
  google_fonts: ^4.0.4  
  firebase_core: ^2.13.0
  photo_view: ^0.14.0
  google_static_maps_controller: ^1.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo_logo.png"
  min_sdk_android: 21

dependency_overrides:
  firebase_core_platform_interface: ^4.5.1

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
        - asset: fonts/Raleway-BoldItalic.ttf
        - asset: fonts/Raleway-Black.ttf
  assets:
    - images/matematike.png
    - images/financa.png
    - images/kimi.png
    - images/gjeografi.png
    - images/kompjuterike.png
    - images/fizike.png
    - images/biologji.png
    - images/answer.png
    - images/logo_login.png
    - images/logo_logo.png
